### ISSUE TITLE
Publish coverage to codecov?

### ISSUE THREAD

**Issue by CosmicHorrorDev** [typst/ecow#15]
Wanted to check before I go ahead and open a PR, but would you be fine with a CI job to publish code coverage information to codecov? I'm planning on adding property testing and fuzzing, and having code coverage information published would be helpful (and you can get a cool little badge for it)

**Comment by laurmaedje** [comment]
Fuzzing sounds great. I wanted to do it, but am too busy unfortunately. I will take a look at codecov.

**Comment by laurmaedje** [comment]
What would uploading the coverage to codecov give us in contrast to just running cargo-tarpaulin locally?

**Comment by CosmicHorrorDev** [comment]
A better interface for looking through coverage, a way of tracking changes over time (catching if a change significantly changes coverage when it shouldn't), and a flashy badge for anyone who is interested in the coverage of their deps

None of those are really crucial, but surely still nice-to-haves

**Comment by laurmaedje** [comment]
If it helps with yor testing plan, I'm on board with it!
