### ISSUE TITLE
Ref counted types missing pointer comparison optimization for `eq`

### ISSUE THREAD

**Issue by epage** [typst/ecow#35]
`Arc<str>` [compares pointers first](https://doc.rust-lang.org/src/alloc/sync.rs.html#3025)  which normal reference equality checks do not perform.

See https://htmlpreview.github.io/?https://github.com/epage/string-benchmarks-rs/blob/master/runs/2023-10-10/eq/report/index.html for a benchmark showcasing the behavior from this

**Comment by laurmaedje** [comment]
Good catch, should be easy enough to fix.

**Comment by laurmaedje** [comment]
The `PartialEq` impl of `Arc<T>` only does this if `T: Eq` because of irreflexive impls, so it looks like this would need specialization for `EcoVec`. :/

For `EcoString`, it would work although I wonder whether it adds more overhead than it's worth for small strings.

**Comment by laurmaedje** [comment]
Sounds good.
